apiVersion: v2
name: trove
description: A Helm chart for openstack trove
type: application
version: 2.1.0
appVersion: 25.0.0-26-g6b3ad1ce-4-11
sources:
- https://github.com/NeCTAR-RC/trove-helm.git
dependencies:
- name: nectarlib
  version: 4.1.0
  repository: oci://registry.rc.nectar.org.au/nectar-helm
